<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Foundation\Http\Middleware\VerifyCsrfToken as Middleware;

class VerifyCsrfToken extends Middleware
{
    protected $addHttpCookie = true;
    public function handle($request, Closure $next)
    {
        $response = $next($request);
        $response->header('P3P','CP="IDC DSP COR ADM DEVi TATi PSA PSD IVAi IVDi CONi HIS OUR IND CNT');
        return $response;
        //return parent::handle($request, $next); // TODO: Change the autogenerated stub
    }

    /**
     * The URIs that should be excluded from CSRF verification.
     *
     * @var array
     */
    protected $except = [
        '/member/company/csrf_token',
        '/member/company/{userIdx}',
        '/member/update-wait',
        '/member/checkUsingBusinessNumber'
    ];
}
